name: Run the test automation manually
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform: "Android" or "iOS"'
        required: true
      marker:
        description: 'Select tests you want to run, e.g. "facebook"'
        required: true
        

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.platform }}!"
          echo "- in ${{ github.event.inputs.marker }}!"
